<h3 style="text-align:center">Agregar categoria</h2>
	<hr>
	<div class="container">
		<div class="col-sm-4 col-sm-offset-4">
			<form action="<?php echo APP_URL.'categorias/agregar'; ?>" method="POST">
				<label for="nombre">Nombre</label>
				<div class="input-group">			
					<input type="text" name="nombre" class="form-control">
					<div class="input-group-append">
					<button class="btn btn-sm btn-success" action="submit">Guardar</button>
				</div>
			</div>
		</form>
	</div>
</div>