<h3 style="text-align:center">Agregar tarea</h2>
<hr>
<div class="container">
	<div class="col-sm-4 col-sm-offset-4">
		<form class="form form-group" action="<?php echo APP_URL."tareas/agregar"; ?>" method="POST">
			<div class="form-group">
			<label for="nombre">Nombre</label>
			<input type="text" name="nombre" class="form-control">
			</div>

			<label for="descripcion">Descripcion</label>
			<textarea name="descripcion" cols="10" rows="5" class="form-control"></textarea>

			<label for="fecha">Fecha</label>
			<input type="date" name="fecha" value="<?php echo date('Y-m-d'); ?>" class="form-control">

			<label for="prioridad">Prioridad</label>
			<input type="range" name="prioridad" min="0" max="10" class="form-control">

			<label for="categoria">Categoria</label>
			<select name="categoria" class="form-control">
				<?php 
					foreach ($this->categorias as $categoria) {
					echo "<option value=".$categoria[0].">".$categoria[1]."</option>";
					}
				?>
			</select>
			<button type="submit" class="btn btn-primary">Guardar</button>
		</form>
	</div>
</div>